steps:
  - name: gcr.io/cloud-builders/docker
    args: [ 'build', '-t', 'gcr.io/$_GCP_PROJECT_ID/$_SERVICE_NAME:$_IMAGE_V', '.' ]
  - name: gcr.io/cloud-builders/docker
    args: [ 'push', 'gcr.io/$_GCP_PROJECT_ID/$_SERVICE_NAME:$_IMAGE_V' ]
  - name: gcr.io/cloud-builders/gcloud
    args: [
      'run',
      'deploy',
      '$_SERVICE_NAME-$_IMAGE_V',
      '--image',
      'gcr.io/$_GCP_PROJECT_ID/$_SERVICE_NAME:$_IMAGE_V',
      '--region', 'us-east1',
      '--platform', 'managed',
      '--port=$_PORT',
      '--set-env-vars=CUSTOMER_USER_SVC_ADDRESS=$_CUSTOMER_USER_SVC_ADDRESS,ORDERS_SVC_ADDRESS=$_ORDERS_SVC_ADDRESS,RESTAURANT_SVC_ADDRESS=$_RESTAURANT_SVC_ADDRESS,CLIENT_SVC_ADDRESS=$_CLIENT_SVC_ADDRESS,AUTH0_ISSUER_BASE_URL=$_AUTH0_ISSUER_BASE_URL,AUTH0_AUDIENCE=$_AUTH0_AUDIENCE,CLOUDINARY_SVC_ADDRESS=$_CLOUDINARY_SVC_ADDRESS,CMS_USER_SVC_ADDRESS=$_CMS_USER_SVC_ADDRESS',
      '--allow-unauthenticated',
    ]
